const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{coins: 0},
	{key: 0},
	{runes: 0},
	{life: 0},
	{isImmune: 0},
	{boss: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{player: 0},
	{Teclado: 0},
	{background_layer1: 0},
	{background_layer2: 0},
	{background_layer3: 0},
	{background_layer4: 0},
	{background_layer5: 0},
	{Sólido: 0},
	{bricks: 0},
	{bricks_left: 0},
	{bricks_right: 0},
	{skin1: 0},
	{grass1: 0},
	{grass2: 0},
	{grass3: 0},
	{ladder1: 0},
	{ladder2: 0},
	{ladder3: 0},
	{tree1: 0},
	{tree2: 0},
	{tree3: 0},
	{box1: 0},
	{bushe1: 0},
	{Senóide: 0},
	{Close: 0},
	{chest: 0},
	{coins_bar: 0},
	{portal: 0},
	{construct_portal: 0},
	{construct_portal2: 0},
	{rune: 0},
	{rune_bar: 0},
	{Áudio: 0},
	{dead_zone: 0},
	{Mouse: 0},
	{inicio_fim: 0},
	{title: 0},
	{EntradaDeTexto: 0},
	{play_button: 0},
	{skin2: 0},
	{tree4: 0},
	{bushe2: 0},
	{x_snake: 0},
	{snake: 0},
	{life_bar: 0},
	{skin_bridge_7: 0},
	{skin3: 0},
	{box2: 0},
	{x_scorpion: 0},
	{scorpion: 0},
	{skin4: 0},
	{x_vulture: 0},
	{vulture: 0},
	{skin5: 0},
	{skin_bridge_5: 0},
	{skin_bridge_6: 0},
	{skin_bridge_7_2: 0},
	{x_boss: 0},
	{mother_turtle: 0},
	{Projétil: 0},
	{bullet: 0},
	{ScrollTo: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{screen: 0},
	{final_text: 0},
	{totalCoins: 0},
	{total_coins: 0},
	{init_button: 0},
	{skin_bridge_7_3: 0},
	{isImmuneFinal: 0},
	{motherTurtleIsDead: 0},
	{clock: 0},
	{bossFight: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	background_layer1: class extends self.ISpriteInstance {},
	background_layer2: class extends self.ISpriteInstance {},
	background_layer3: class extends self.ISpriteInstance {},
	background_layer4: class extends self.ISpriteInstance {},
	background_layer5: class extends self.ISpriteInstance {},
	bricks: class extends self.ISpriteInstance {},
	bricks_left: class extends self.ISpriteInstance {},
	bricks_right: class extends self.ISpriteInstance {},
	skin1: class extends self.ITilemapInstance {},
	grass1: class extends self.ISpriteInstance {},
	grass2: class extends self.ISpriteInstance {},
	grass3: class extends self.ISpriteInstance {},
	ladder1: class extends self.ISpriteInstance {},
	ladder2: class extends self.ISpriteInstance {},
	ladder3: class extends self.ISpriteInstance {},
	tree1: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	tree3: class extends self.ISpriteInstance {},
	box1: class extends self.ISpriteInstance {},
	bushe1: class extends self.ISpriteInstance {},
	coins: class extends self.ISpriteInstance {},
	chest: class extends self.ISpriteInstance {},
	coins_bar: class extends self.ISpriteFontInstance {},
	key: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	construct_portal: class extends self.ISpriteFontInstance {},
	construct_portal2: class extends self.ISpriteFontInstance {},
	rune: class extends self.ISpriteInstance {},
	rune_bar: class extends self.ISpriteFontInstance {},
	Áudio: class extends self.IInstance {},
	dead_zone: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	title: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	play_button: class extends self.ISpriteInstance {},
	skin2: class extends self.ITilemapInstance {},
	tree4: class extends self.ISpriteInstance {},
	bushe2: class extends self.ISpriteInstance {},
	snake: class extends self.ISpriteInstance {},
	life_bar: class extends self.ISpriteInstance {},
	skin_bridge_7: class extends self.ITilemapInstance {},
	skin3: class extends self.ITilemapInstance {},
	box2: class extends self.ISpriteInstance {},
	scorpion: class extends self.ISpriteInstance {},
	skin4: class extends self.ITilemapInstance {},
	vulture: class extends self.ISpriteInstance {},
	skin5: class extends self.ITilemapInstance {},
	skin_bridge_5: class extends self.ITilemapInstance {},
	skin_bridge_6: class extends self.ITilemapInstance {},
	skin_bridge_7_2: class extends self.ITilemapInstance {},
	mother_turtle: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	screen: class extends self.ISpriteInstance {},
	final_text: class extends self.ISpriteFontInstance {},
	total_coins: class extends self.ISpriteFontInstance {},
	init_button: class extends self.ISpriteInstance {},
	skin_bridge_7_3: class extends self.ITilemapInstance {}
}